-- Script para crear la tabla 'jugadores' en tu nuevo proyecto de Supabase
-- Ejecuta este código en el "SQL Editor" de tu panel de Supabase:

CREATE TABLE IF NOT EXISTS public.jugadores (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  nombre text,
  fecha_nacimiento text,
  padres text,
  hermanos text,
  pareja text,
  mascota text,
  hobby text,
  comida_favorita text,
  color_favorito text,
  artista text,
  pelicula text,
  password text
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.jugadores ENABLE ROW LEVEL SECURITY;

-- Crear políticas para permitir lectura e inserción pública (necesario para el juego)
CREATE POLICY "Permitir lectura publica" ON public.jugadores
  FOR SELECT USING (true);

CREATE POLICY "Permitir insercion publica" ON public.jugadores
  FOR INSERT WITH CHECK (true);
